"""initial schema

Revision ID: 82c106cacc45
Revises: 
Create Date: 2026-07-02 17:12:48.396582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82c106cacc45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Esquema para el checkpointer de LangGraph (Fase 3, PostgresSaver.setup()).
    # Se crea aqui (namespace vacio) porque Alembic es el unico mecanismo de
    # migraciones del repo; las tablas dentro de este esquema las gestiona
    # PostgresSaver, no Alembic (ver include_object en migrations/env.py).
    op.execute("CREATE SCHEMA IF NOT EXISTS langgraph")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('subcategory', sa.String(length=64), nullable=False),
    sa.Column('types', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('setup_time', sa.Integer(), nullable=False),
    sa.Column('run_time', sa.Integer(), nullable=False),
    sa.Column('evidence_strength', sa.Integer(), nullable=False),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('pairings_before', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pairings_after', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('page_ref', sa.Integer(), nullable=True),
    sa.CheckConstraint('cost BETWEEN 1 AND 5', name=op.f('ck_experiments_cost_range')),
    sa.CheckConstraint('evidence_strength BETWEEN 1 AND 5', name=op.f('ck_experiments_evidence_strength_range')),
    sa.CheckConstraint('run_time BETWEEN 1 AND 5', name=op.f('ck_experiments_run_time_range')),
    sa.CheckConstraint('setup_time BETWEEN 1 AND 5', name=op.f('ck_experiments_setup_time_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('raw_idea', sa.Text(), nullable=False),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('blueprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'awaiting_input', 'done')", name=op.f('ck_blueprints_status_valid')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_blueprints_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blueprints'))
    )
    op.create_index(op.f('ix_blueprints_project_id'), 'blueprints', ['project_id'], unique=False)
    op.create_index(op.f('ix_blueprints_thread_id'), 'blueprints', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blueprints_thread_id'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_project_id'), table_name='blueprints')
    op.drop_table('blueprints')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('experiments')
    # ### end Alembic commands ###

    # Nota: el esquema `langgraph` NO se elimina aqui a proposito. Su ciclo de
    # vida (tablas) lo controla PostgresSaver (Fase 3), fuera del alcance de
    # esta migracion de negocio; un downgrade de `public` no debe arrastrar
    # datos de otro subsistema.
